# A wrapper generated by claude(cursor)
import numpy as np
import torch
from typing import Optional, Dict, Any
from omegaconf import DictConfig 
from .RawBoost.data_utils_rawboost import process_Rawboost_feature, get_default_args

from onebit.data.augmentors.registry import AugmentorRegistry
from onebit.data.augmentors.base import BaseAugmentor
from onebit.config import ConfigManager

@AugmentorRegistry.register('rawboost')
class RawBoostAugmentation(BaseAugmentor):
    """
    RawBoost augmentation wrapper that provides a clean interface for audio data augmentation.
    
    This class wraps the existing RawBoost library and provides default settings
    for easy use in the OneBit data pipeline.
    """
    
    def __init__(
        self,
        config_manager: ConfigManager
    ):
        super().__init__(config_manager)
        data_config = config_manager.get_data_config()
        
        # Read from the correct config path: data.aug.rawboost
        rawboost_config = data_config.aug.rawboost
        algorithm: int = getattr(rawboost_config, 'algorithm', 5)
        probability = getattr(rawboost_config, 'probability', 0.5) 
        sample_rate: int = getattr(rawboost_config, 'sample_rate', 16_000)
        """
        Initialize RawBoost augmentation.
        
        Args:
            algorithm: RawBoost algorithm number (0-8)
                0: No augmentation
                1: LnL_convolutive_noise
                2: ISD_additive_noise
                3: SSI_additive_noise
                4: Series combination (1+2+3)
                5: Series combination (1+2) - Default
                6: Series combination (1+3)
                7: Series combination (2+3)
                8: Parallel combination (1||2)
            probability: Probability of applying augmentation
            sample_rate: Audio sample rate
        """
        self.algorithm = algorithm
        self.probability = probability
        self.sample_rate = sample_rate
        default_args = get_default_args()
        self.parameters = default_args
    
    def __call__(self, audio: np.ndarray) -> np.ndarray:
        """
        Apply RawBoost augmentation to audio.
        
        Args:
            audio: Input audio as numpy array
            
        Returns:
            Augmented audio as numpy array
        """
        # Check if augmentation should be applied
        if np.random.random() > self.probability:
            return audio
        
        # Apply RawBoost augmentation
        try:
            augmented_audio = process_Rawboost_feature(
                feature=audio,
                sr=self.sample_rate,
                args=self.parameters,
                algo=self.algorithm
            )
            return augmented_audio
        except Exception as e:
            print(f"Warning: RawBoost augmentation failed, returning original audio: {e}")
            return audio
    
    def apply_to_tensor(self, audio_tensor: torch.Tensor) -> torch.Tensor:
        """
        Apply RawBoost augmentation to PyTorch tensor.
        
        Args:
            audio_tensor: Input audio as PyTorch tensor
            
        Returns:
            Augmented audio as PyTorch tensor
        """
        # Convert tensor to numpy
        audio_np = audio_tensor.numpy()
        
        # Apply augmentation
        augmented_np = self(audio_np)
        
        # Convert back to tensor
        return torch.from_numpy(augmented_np).float()
    
    def get_algorithm_description(self) -> str:
        """
        Get description of the current algorithm.
        
        Returns:
            String description of the algorithm
        """
        descriptions = {
            0: "No augmentation",
            1: "Linear and non-linear convolutive noise",
            2: "Impulsive signal-dependent noise",
            3: "Stationary signal-independent noise",
            4: "Series combination (1+2+3)",
            5: "Series combination (1+2)",
            6: "Series combination (1+3)",
            7: "Series combination (2+3)",
            8: "Parallel combination (1||2)"
        }
        return descriptions.get(self.algorithm, f"Unknown algorithm {self.algorithm}")
    
    def __repr__(self) -> str:
        """String representation of the augmentation."""
        return (f"RawBoostAugmentation(algorithm={self.algorithm}, "
                f"probability={self.probability}, sample_rate={self.sample_rate})")

if __name__ == '__main__':
    import sys
    import soundfile as sf
    from pathlib import Path
    
    if len(sys.argv) < 2:
        print("Usage: python rawboost.py <output_dir> [audio_file]")
        sys.exit(1)
    
    output_dir = Path(sys.argv[1])
    audio_file = sys.argv[2] if len(sys.argv) > 2 else "./tmp/test.flac"
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    config_path = "onebit/configs/test.yaml"
    config_manager = ConfigManager(config_path)
    cli_args_dict = {
        "data.aug.rawboost.probability": 1.0
    }
    config_manager.merge_with_cli(cli_args_dict)
    
    rawboost_augmentor = RawBoostAugmentation(config_manager)
    
    from onebit.data import audio_util
    audio_array, sr = audio_util.get_audio(audio_file, trim_sil=False)
    augmented = rawboost_augmentor(audio_array)
    
    output_path = output_dir / "rawboost.wav"
    sf.write(str(output_path), augmented, sr)
    print(f"Augmented audio saved to {output_path}")